apiVersion: apps/v1
kind: Deployment
metadata: { name: zookeeper-deployment, namespace: tenant-app }
spec:
  replicas: 1
  selector: { matchLabels: { app: zookeeper } }
  template:
    metadata: { labels: { app: zookeeper } }
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.0.1
          ports: [{ containerPort: 2181 }]
          env:
          - name: ZOOKEEPER_CLIENT_PORT
            value: "2181"
          - name: ZOOKEEPER_TICK_TIME
            value: "2000"
          - name: ZOOKEEPER_SERVER_ID
            value: "1"
          - name: ZOOKEEPER_SERVERS
            value: "0.0.0.0:2888:3888"
---
apiVersion: v1
kind: Service
metadata: { name: zookeeper-service, namespace: tenant-app }
spec:
  selector: { app: zookeeper }
  ports: [{ port: 2181 }]

---
apiVersion: apps/v1
kind: Deployment
metadata: { name: kafka-deployment, namespace: tenant-app }
spec:
  replicas: 1
  selector: { matchLabels: { app: kafka } }
  template:
    metadata: { labels: { app: kafka } }
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.0.1
          ports: [{ containerPort: 9092 }]
          env:
          - name: KAFKA_BROKER_ID
            value: "1"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "zookeeper-service.tenant-app.svc.cluster.local:2181"
          - name: KAFKA_LISTENERS
            value: "PLAINTEXT://0.0.0.0:9092"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "PLAINTEXT://kafka-service.tenant-app.svc.cluster.local:9092"
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            value: "1"
---
apiVersion: v1
kind: Service
metadata: { name: kafka-service, namespace: tenant-app }
spec:
  selector: { app: kafka }
  ports: [{ port: 9092 }]

---
apiVersion: apps/v1
kind: Deployment
metadata: { name: schema-registry-deployment, namespace: tenant-app }
spec:
  replicas: 1
  selector: { matchLabels: { app: schema-registry } }
  template:
    metadata: { labels: { app: schema-registry } }
    spec:
      containers:
        - name: schema-registry
          image: confluentinc/cp-schema-registry:7.0.1
          ports: [{ containerPort: 8081 }]
          env:
          - name: SCHEMA_REGISTRY_HOST_NAME
            value: "schema-registry-service"
          - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
            value: "zookeeper-service.tenant-app.svc.cluster.local:2181"
          - name: SCHEMA_REGISTRY_LISTENERS
            value: "http://0.0.0.0:8081"
---
apiVersion: v1
kind: Service
metadata: { name: schema-registry-service, namespace: tenant-app }
spec:
  selector: { app: schema-registry }
  ports: [{ port: 8081 }]
